<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<title>Assignments</title>
		<link rel="stylesheet" type="text/css" href="archive.css"/>
		<link rel="stylesheet" type="text/css" href="topbar.css"/>
		<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
		<script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.3.1.min.js"></script>

		<?php
			$items = array();
			$items['hello.html'] = "Prove01 - Hello World";
			$items['home.php'] = "Prove02 - Home Page";
		?>
	</head>
	<body>
		<ul id="topbar">
         	<li><a href="home.php"><i class="fa fa-home"></i></a></li>
         	<li><a class="active" href="archive.php"><i class="fa fa-archive"></i></a></li>
         	<li><a class="active" href="archive.php">CS 313 Assignments</a></li>
        </ul>
		<div id="page">
			<div id="assignlist">
				<span id="invisible">List Generated by PHP</span>
				<ul>
					<?php
						foreach ($items as $key => $value) {
							echo "<li><a href=\"" . $key . "\">" . $value . "</a></li>";
						}
					?>
				</ul>
			</div>
		</div>
	</body>
</html>
